git:
  depth: 5
stages:
- "Build and Test"
- "Package"
jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
    - cd sample-application-backend
    script:
    - echo "Maven build"
    - echo "Run test coverage and Quality Gate"
  - stage: "Build and Test"
    language: node.js
    node_js: '12.20'
    before_script:
    - cd sample-application-frontend
    script:
    - echo "NPM install and build"
    - npm install
    - npm run lint
    - npm run test
    
    
  - stage: "Package"
    before_script:
    - cd sample-application-backend
    script:
    - echo "Docker build ..."
    - docker build -t lotarie73/app-backend .
    - echo "Docker login ..."
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    - echo "Docker push ..."
    - docker push lotarie73/app-backend
    
  - stage: "Package"
    before_script:
    - cd sample-application-frontend
    script:
    - echo "Docker build ..."
    - docker build -t lotarie73/app-frontend .
    - echo "Docker login ... "
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    - echo "Docker push ..."
    - docker push lotarie73/app-frontend

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"
services:
- docker
